import matplotlib.pyplot as plt
import json
import os
import numpy as np

# Path to the results file generated by main_runner.py
RESULTS_FILE = "research_results.json"

def plot_results():
    if not os.path.exists(RESULTS_FILE):
        print("No results file found to plot.")
        return

    with open(RESULTS_FILE, 'r') as f:
        data = json.load(f)

    # Filter out empty entries
    models = []
    fids = []
    f1s = []

    # Expected order for the paper
    order = ["baseline", "dcgan_diffaug", "lightweight_gan", "projected_gan", "stylegan2_ada"]
    
    # Process data in specific order if available, otherwise just list them
    for name in order:
        if name in data:
            models.append(name.replace("_", " ").upper()) # Make labels pretty
            fids.append(data[name].get("fid", 0))
            f1s.append(data[name].get("f1", 0))

    if not models:
        print("No data available to plot.")
        return

    # --- PLOT 1: FID SCORES (Lower is Better) ---
    plt.figure(figsize=(10, 6))
    bars = plt.bar(models, fids, color=['#e74c3c' if 'BASELINE' not in m else '#95a5a6' for m in models])
    plt.ylabel('FID Score (Lower is Better)', fontsize=12)
    plt.title('Visual Realism Comparison (FID)', fontsize=14)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    
    # Add numbers on top of bars
    for bar in bars:
        height = bar.get_height()
        if height > 0:
            plt.text(bar.get_x() + bar.get_width()/2., height + 1,
                     f'{height:.1f}', ha='center', va='bottom')
    
    plt.savefig('result_chart_fid.png')
    print("Saved chart: result_chart_fid.png")

    # --- PLOT 2: F1 SCORES (Higher is Better) ---
    plt.figure(figsize=(10, 6))
    # Green for good models, Grey for baseline
    colors = ['#2ecc71' if 'BASELINE' not in m else '#7f8c8d' for m in models]
    bars = plt.bar(models, f1s, color=colors)
    plt.ylabel('F1-Score (Higher is Better)', fontsize=12)
    plt.title('Classifier Utility Comparison (F1-Score)', fontsize=14)
    plt.ylim(0, 1.0) # F1 is always between 0 and 1
    plt.grid(axis='y', linestyle='--', alpha=0.7)

    # Add numbers on top
    for bar in bars:
        height = bar.get_height()
        if height > 0:
            plt.text(bar.get_x() + bar.get_width()/2., height + 0.01,
                     f'{height:.3f}', ha='center', va='bottom')

    plt.savefig('result_chart_f1.png')
    print("Saved chart: result_chart_f1.png")

if __name__ == "__main__":
    plot_results()